#!/bin/sh

echo installetion SPM

string=`g++ -print-search-dirs`

IFS=':' read -r a second a fourth a <<-_EOF_
$string
_EOF_

echo $second

cp ./*.h /usr/include/
cp ./build/libSPM.a $second

echo "files installed to /usr/include/"
echo ./*.h
echo "libSPM.a installed to $second"
